/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_food_free(a: number): void;
export function __wbg_get_food_x(a: number): number;
export function __wbg_set_food_x(a: number, b: number): void;
export function __wbg_get_food_y(a: number): number;
export function __wbg_set_food_y(a: number, b: number): void;
export function food_get_color(a: number, b: number): void;
export function __wbg_game_free(a: number): void;
export function game_new(): number;
export function game_play(a: number): void;
export function __wbg_coord_free(a: number): void;
export function __wbg_get_coord_x(a: number): number;
export function __wbg_set_coord_x(a: number, b: number): void;
export function __wbg_get_coord_y(a: number): number;
export function __wbg_set_coord_y(a: number, b: number): void;
export function __wbg_node_free(a: number): void;
export function __wbg_get_node_coord(a: number): number;
export function __wbg_set_node_coord(a: number, b: number): void;
export function __wbg_get_node_direction(a: number): number;
export function __wbg_set_node_direction(a: number, b: number): void;
export function node_new(a: number, b: number, c: number): number;
export function node_random(a: number): number;
export function __wbg_snake_free(a: number): void;
export function __wbg_get_snake_size(a: number): number;
export function __wbg_set_snake_size(a: number, b: number): void;
export function snake_new(): number;
export function snake_grow_snake(a: number): void;
export function snake_get_snake_body(a: number, b: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h75fe3f06a608e52f(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h64837940442244bd(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
